"""initial schema

Revision ID: 279913d4d888
Revises: 
Create Date: 2026-06-18 00:59:19.325831
"""
from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

import us_watcher.db.types

revision: str = '279913d4d888'
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audit_events',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('action', sa.String(length=64), nullable=False),
    sa.Column('entity_type', sa.String(length=48), nullable=True),
    sa.Column('entity_id', sa.String(length=64), nullable=True),
    sa.Column('summary', sa.Text(), nullable=False),
    sa.Column('payload', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('audit_events', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_audit_events_action'), ['action'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_events_created_at'), ['created_at'], unique=False)

    op.create_table('daily_briefings',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('briefing_date', sa.String(length=16), nullable=False),
    sa.Column('briefing_type', sa.String(length=16), nullable=False),
    sa.Column('language', sa.String(length=8), nullable=False),
    sa.Column('headline', sa.Text(), nullable=False),
    sa.Column('payload', sa.JSON(), nullable=False),
    sa.Column('generated_by', sa.String(length=16), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('daily_briefings', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_daily_briefings_briefing_date'), ['briefing_date'], unique=False)
        batch_op.create_index('ux_briefing_unique', ['briefing_date', 'briefing_type', 'language'], unique=True)

    op.create_table('data_quality_events',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('kind', sa.String(length=48), nullable=False),
    sa.Column('symbol', sa.String(length=32), nullable=True),
    sa.Column('detail', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('data_quality_events', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_data_quality_events_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_data_quality_events_kind'), ['kind'], unique=False)

    op.create_table('instruments',
    sa.Column('symbol', sa.String(length=32), nullable=False),
    sa.Column('name', sa.String(length=160), nullable=False),
    sa.Column('group', sa.String(length=32), nullable=False),
    sa.Column('asset_type', sa.String(length=32), nullable=True),
    sa.Column('market', sa.String(length=32), nullable=True),
    sa.Column('gics', sa.String(length=64), nullable=True),
    sa.Column('yahoo_symbol', sa.String(length=32), nullable=True),
    sa.Column('is_proxy', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('symbol')
    )
    op.create_table('macro_observations',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('series_id', sa.String(length=64), nullable=False),
    sa.Column('observation_date', sa.String(length=16), nullable=False),
    sa.Column('value', sa.Float(), nullable=False),
    sa.Column('vintage_date', sa.String(length=16), nullable=True),
    sa.Column('available_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('source', sa.String(length=32), nullable=False),
    sa.Column('ingested_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('macro_observations', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_macro_observations_series_id'), ['series_id'], unique=False)
        batch_op.create_index('ix_macro_series_obs', ['series_id', 'observation_date', 'vintage_date'], unique=False)

    op.create_table('model_usage',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('run_id', sa.String(length=64), nullable=True),
    sa.Column('provider', sa.String(length=32), nullable=False),
    sa.Column('model', sa.String(length=64), nullable=False),
    sa.Column('role', sa.String(length=24), nullable=False),
    sa.Column('input_tokens', sa.Integer(), nullable=False),
    sa.Column('output_tokens', sa.Integer(), nullable=False),
    sa.Column('cost_usd', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('model_usage', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_model_usage_run_id'), ['run_id'], unique=False)

    op.create_table('news_clusters',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('headline', sa.Text(), nullable=False),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('importance', sa.Float(), nullable=False),
    sa.Column('article_count', sa.Integer(), nullable=False),
    sa.Column('first_seen', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_seen', sa.DateTime(timezone=True), nullable=False),
    sa.Column('related', sa.JSON(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('news_clusters', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_news_clusters_last_seen'), ['last_seen'], unique=False)

    op.create_table('orchestrator_runs',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('objective', sa.String(length=64), nullable=False),
    sa.Column('trigger', sa.String(length=64), nullable=False),
    sa.Column('status', sa.String(length=24), nullable=False),
    sa.Column('selected_agents', sa.JSON(), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('runtime', sa.String(length=16), nullable=False),
    sa.Column('token_usage', sa.Integer(), nullable=False),
    sa.Column('cost_usd', sa.Float(), nullable=False),
    sa.Column('payload', sa.JSON(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('orchestrator_runs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_orchestrator_runs_started_at'), ['started_at'], unique=False)

    op.create_table('pipeline_locks',
    sa.Column('key', sa.String(length=96), nullable=False),
    sa.Column('holder', sa.String(length=64), nullable=False),
    sa.Column('acquired_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('key')
    )
    op.create_table('pipeline_runs',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('pipeline', sa.String(length=48), nullable=False),
    sa.Column('status', sa.String(length=24), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('detail', sa.JSON(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('pipeline_runs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_pipeline_runs_pipeline'), ['pipeline'], unique=False)

    op.create_table('recommendations',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('lineage_id', sa.String(length=64), nullable=False),
    sa.Column('revision', sa.Integer(), nullable=False),
    sa.Column('change_type', sa.String(length=24), nullable=False),
    sa.Column('ticker', sa.String(length=32), nullable=False),
    sa.Column('company_name', sa.String(length=160), nullable=False),
    sa.Column('asset_type', sa.String(length=32), nullable=False),
    sa.Column('horizon', sa.String(length=16), nullable=False),
    sa.Column('action', sa.String(length=16), nullable=False),
    sa.Column('total_score', sa.Float(), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('one_line_thesis', sa.Text(), nullable=False),
    sa.Column('as_of', sa.DateTime(timezone=True), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('data_freshness', sa.String(length=16), nullable=False),
    sa.Column('payload', sa.JSON(), nullable=False),
    sa.Column('orchestrator_run_id', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('recommendations', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_recommendations_action'), ['action'], unique=False)
        batch_op.create_index(batch_op.f('ix_recommendations_as_of'), ['as_of'], unique=False)
        batch_op.create_index(batch_op.f('ix_recommendations_horizon'), ['horizon'], unique=False)
        batch_op.create_index(batch_op.f('ix_recommendations_lineage_id'), ['lineage_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_recommendations_ticker'), ['ticker'], unique=False)

    op.create_table('regime_snapshots',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('as_of', sa.DateTime(timezone=True), nullable=False),
    sa.Column('score', sa.Float(), nullable=False),
    sa.Column('regime', sa.String(length=32), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('coverage', sa.Float(), nullable=False),
    sa.Column('payload', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('regime_snapshots', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_regime_snapshots_as_of'), ['as_of'], unique=False)

    op.create_table('agent_runs',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('orchestrator_run_id', sa.String(length=64), nullable=False),
    sa.Column('agent_id', sa.String(length=64), nullable=False),
    sa.Column('status', sa.String(length=24), nullable=False),
    sa.Column('direction', sa.Float(), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('model_name', sa.String(length=64), nullable=True),
    sa.Column('token_usage', sa.Integer(), nullable=False),
    sa.Column('duration_ms', sa.Integer(), nullable=False),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('output', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['orchestrator_run_id'], ['orchestrator_runs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('agent_runs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_agent_runs_orchestrator_run_id'), ['orchestrator_run_id'], unique=False)

    op.create_table('news_articles',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('title', sa.Text(), nullable=False),
    sa.Column('normalized_title', sa.Text(), nullable=False),
    sa.Column('url', sa.Text(), nullable=False),
    sa.Column('canonical_url', sa.Text(), nullable=True),
    sa.Column('publisher', sa.String(length=160), nullable=False),
    sa.Column('language', sa.String(length=8), nullable=False),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('published_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('ingested_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('importance', sa.Float(), nullable=False),
    sa.Column('reliability', sa.Float(), nullable=False),
    sa.Column('sentiment', sa.Float(), nullable=True),
    sa.Column('cluster_id', sa.String(length=64), nullable=True),
    sa.Column('related', sa.JSON(), nullable=False),
    sa.Column('content_hash', sa.String(length=64), nullable=False),
    sa.ForeignKeyConstraint(['cluster_id'], ['news_clusters.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('news_articles', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_news_articles_content_hash'), ['content_hash'], unique=False)
        batch_op.create_index(batch_op.f('ix_news_articles_published_at'), ['published_at'], unique=False)

    op.create_table('recommendation_outcomes',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('recommendation_id', sa.String(length=64), nullable=False),
    sa.Column('lineage_id', sa.String(length=64), nullable=False),
    sa.Column('horizon_days', sa.Integer(), nullable=False),
    sa.Column('entry_price', us_watcher.db.types.DecimalString(), nullable=True),
    sa.Column('exit_price', us_watcher.db.types.DecimalString(), nullable=True),
    sa.Column('abs_return_pct', sa.Float(), nullable=True),
    sa.Column('benchmark', sa.String(length=32), nullable=True),
    sa.Column('excess_return_pct', sa.Float(), nullable=True),
    sa.Column('evaluated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['recommendation_id'], ['recommendations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('recommendation_outcomes', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_recommendation_outcomes_lineage_id'), ['lineage_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_recommendation_outcomes_recommendation_id'), ['recommendation_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('recommendation_outcomes', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_recommendation_outcomes_recommendation_id'))
        batch_op.drop_index(batch_op.f('ix_recommendation_outcomes_lineage_id'))

    op.drop_table('recommendation_outcomes')
    with op.batch_alter_table('news_articles', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_news_articles_published_at'))
        batch_op.drop_index(batch_op.f('ix_news_articles_content_hash'))

    op.drop_table('news_articles')
    with op.batch_alter_table('agent_runs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_agent_runs_orchestrator_run_id'))

    op.drop_table('agent_runs')
    with op.batch_alter_table('regime_snapshots', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_regime_snapshots_as_of'))

    op.drop_table('regime_snapshots')
    with op.batch_alter_table('recommendations', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_recommendations_ticker'))
        batch_op.drop_index(batch_op.f('ix_recommendations_lineage_id'))
        batch_op.drop_index(batch_op.f('ix_recommendations_horizon'))
        batch_op.drop_index(batch_op.f('ix_recommendations_as_of'))
        batch_op.drop_index(batch_op.f('ix_recommendations_action'))

    op.drop_table('recommendations')
    with op.batch_alter_table('pipeline_runs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_pipeline_runs_pipeline'))

    op.drop_table('pipeline_runs')
    op.drop_table('pipeline_locks')
    with op.batch_alter_table('orchestrator_runs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_orchestrator_runs_started_at'))

    op.drop_table('orchestrator_runs')
    with op.batch_alter_table('news_clusters', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_news_clusters_last_seen'))

    op.drop_table('news_clusters')
    with op.batch_alter_table('model_usage', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_model_usage_run_id'))

    op.drop_table('model_usage')
    with op.batch_alter_table('macro_observations', schema=None) as batch_op:
        batch_op.drop_index('ix_macro_series_obs')
        batch_op.drop_index(batch_op.f('ix_macro_observations_series_id'))

    op.drop_table('macro_observations')
    op.drop_table('instruments')
    with op.batch_alter_table('data_quality_events', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_data_quality_events_kind'))
        batch_op.drop_index(batch_op.f('ix_data_quality_events_created_at'))

    op.drop_table('data_quality_events')
    with op.batch_alter_table('daily_briefings', schema=None) as batch_op:
        batch_op.drop_index('ux_briefing_unique')
        batch_op.drop_index(batch_op.f('ix_daily_briefings_briefing_date'))

    op.drop_table('daily_briefings')
    with op.batch_alter_table('audit_events', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_audit_events_created_at'))
        batch_op.drop_index(batch_op.f('ix_audit_events_action'))

    op.drop_table('audit_events')
    # ### end Alembic commands ###
